import crcjam from 'crc/crcjam';

/**
 * JAMCRC: CRC-32/JAMCRC — the bitwise complement of standard CRC-32,
 * masked to 31 bits. Matches the Python reference:
 * `(zlib.crc32(s.encode()) ^ 0xFFFFFFFF) & 0x7FFFFFFF`
 */
export function jamcrc(str: string): number {
  // crc/crcjam returns CRC-32/JAMCRC (inverted CRC-32)
  // We mask to 31 bits to match the game's convention
  return crcjam(Buffer.from(str)) & 0x7fffffff;
}

// All known type-name → extension mappings from the game.
// Key = JAMCRC hash of the rType name, Value = file extension (with dot)
const TYPE_EXT_PAIRS: [string, string][] = [
  ['rAchievementInfo', '.acif'],
  ['rArmorSet', '.ams'],
  ['rSoundAttributeSe', '.ase'],
  ['rBodyData', '.bdd'],
  ['rBlockList', '.bld'],
  ['rBugiStrengthenNeedMaterialTable', '.bsmt'],
  ['rBugiStrengthenNeedZenyTable', '.bszt'],
  ['rBlockTable', '.btbl'],
  ['rChargeAxeChargeParam', '.cacp'],
  ['rChainCol', '.ccl'],
  ['rChargeAxeDefDownParam', '.cddp'],
  ['rConditionParam', '.copm'],
  ['rCnsTinyChain', '.ctc'],
  ['rContentSclSet', '.ctss'],
  ['rItemCurrency', '.cui'],
  ['rDefineTable', '.dft'],
  ['rDramaInfo', '.dinf'],
  ['rItemDisplay', '.dit'],
  ['rEffect2D', '.e2d'],
  ['rEffectAnim', '.ean'],
  ['rEnemyBaseData', '.ebd'],
  ['rEnemyBugiParam', '.ebp'],
  ['rEnemyBreakName', '.ebrn'],
  ['rEnemyCommonParam', '.ecp'],
  ['rEquipChangeColors', '.ect'],
  ['rEquipChainTable', '.ect'],
  ['rEquipCollectionValueTable', '.ecvt'],
  ['rEnemyDataTable', '.edt'],
  ['rCtcEquipSeriesEffectSet', '.ees'],
  ['rCtcEquipEffectSet', '.ees'],
  ['rEffectList', '.efl'],
  ['rEffectParam', '.efp'],
  ['rEnemyList', '.eli'],
  ['rEnemyCmd', '.emc'],
  ['rEnemyStatus', '.ems'],
  ['rExploreNoteContent', '.enc'],
  ['rEventNodeSheet', '.ensh'],
  ['rEffectParamEnemy', '.epe'],
  ['rEquipPierceTable', '.ept'],
  ['rEquipPotentialValue', '.epv'],
  ['rEquipEffectTable', '.eqet'],
  ['rEquipHint', '.eqh'],
  ['rEquipSkillPack', '.eqpk'],
  ['rEquipSeries', '.eqs'],
  ['rEquipSkillAntiField', '.esaf'],
  ['rEquipSkillEventPoint', '.esep'],
  ['rEquipSkillParam', '.esp'],
  ['rEffectSequence', '.esq'],
  ['rEquipSkillEventSuicideAttack', '.essa'],
  ['rEquipSoundTable', '.est'],
  ['rEventBannerPath', '.evbn'],
  ['rEvolutionEquipTable', '.evet'],
  ['rEventHome', '.evhm'],
  ['rFixedEquipInfo', '.fei'],
  ['rForestEnemyParam', '.fep'],
  ['rFixedEquipSet', '.fes'],
  ['rForestQuestSheet', '.fqs'],
  ['rForestFloorMap', '.fqsh'],
  ['rFieldSkillBlockSet', '.fsbs'],
  ['rFieldSkillParam', '.fspm'],
  ['rFieldSkillSet', '.fsst'],
  ['rForestTechnicalTableSet', '.ftts'],
  ['rFreeUseParam', '.fup'],
  ['rGuildBingoMission', '.gbmd'],
  ['rGUIFont', '.gfd'],
  ['rGunLanceEftTable', '.glet'],
  ['rGUIMessage', '.gmd'],
  ['rGUI', '.gui'],
  ['rHigiParam', '.hgpm'],
  ['rHigiSet', '.hgs'],
  ['rHairData', '.hird'],
  ['rHelmCustomData', '.hlmc'],
  ['rHelmCustomData_4G', '.hlmcg'],
  ['rHelmData', '.hlmd'],
  ['rHelmData_4G', '.hlmdg'],
  ['rHunterRankHint', '.hrh'],
  ['rHitData', '.htd'],
  ['rHitSize', '.hts'],
  ['rItemArtifact', '.iat'],
  ['rItemAugite', '.iaug'],
  ['rItemCollection', '.icl'],
  ['rItemEventPoint', '.iept'],
  ['rItemForestEquipSkill', '.ifes'],
  ['rItemForestNyankenEquipSkill', '.ifne'],
  ['rItemForest', '.ifor'],
  ['rForestRandomTable', '.ifrt'],
  ['rItemForestStamina', '.ifst'],
  ['rItemLimit', '.ilim'],
  ['rItemMaterialSearch', '.imas'],
  ['rItemMaterial', '.imat'],
  ['rItemMatatabi', '.imata'],
  ['rItemPayment', '.ipay'],
  ['rItemPcoin', '.ipcn'],
  ['rItemPartnerGrow', '.ipgr'],
  ['rItemPlusUpMaterial', '.ipmt'],
  ['rItemPower', '.ipow'],
  ['rItemTravel', '.itra'],
  ['rKaridamaPowerUpTable', '.kpu'],
  ['rKatamariInfo', '.ktmi'],
  ['rKariwazaParam', '.kwp'],
  ['rCameraList', '.lcm'],
  ['rMotionList', '.lmt'],
  ['rMapSet', '.map'],
  ['rMonsterAppearInfo', '.mapi'],
  ['rModelNum', '.mdln'],
  ['rMhMotionEffect', '.mef'],
  ['rModel', '.mod'],
  ['rMapData', '.mpd'],
  ['rMonsterPartsManager', '.mpm'],
  ['rMonumentParamType', '.mpt'],
  ['rMaterial', '.mrl'],
  ['rMonumentStrengthenParam', '.msp'],
  ['rMHSoundSequence', '.mss'],
  ['rMonumentTreasureBonus', '.mtb'],
  ['rNodeSheet', '.nsht'],
  ['rNyankenQuest', '.nyqt'],
  ['rOzyamaBombParam', '.obp'],
  ['rOtomoEquipBody', '.oeb'],
  ['rOtomoEquipBodyModel', '.oebm'],
  ['rOtomoEquipHead', '.oeh'],
  ['rOtomoEquipHeadModel', '.oehm'],
  ['rOtomoEquipWeapon', '.oew'],
  ['rOtomoEquipWeaponModel', '.oewm'],
  ['rOtomoGrow', '.ogr'],
  ['rOmamoriSeries', '.oms'],
  ['rOtomoParam', '.opa'],
  ['rOmamoriReleaseTable', '.ort'],
  ['rOceanSheet', '.osht'],
  ['rOtomoSkillMainCommon', '.osmc'],
  ['rOtomoSkillMainGather', '.osmg'],
  ['rOtomoSkillMainHeal', '.osmh'],
  ['rOtomoSkillMainLucky', '.osml'],
  ['rOtomoSkillMainProvoke', '.osmp'],
  ['rOtomoSkillMainPipe', '.osmp'],
  ['rOtomoSkillMainRescue', '.osmr'],
  ['rOtomoSkillMainTrap', '.osmt'],
  ['rOtomoSkillSub', '.oss'],
  ['rOmamoriTriggerTable', '.ott'],
  ['rParamByDangerLv', '.pbdl'],
  ['rPlayerBulletParam', '.pblm'],
  ['rPlayerCmnParam', '.pcp'],
  ['rProofEffectList', '.pel'],
  ['rPartnerEquipVoice', '.pev'],
  ['rPartnerGrowTable', '.pgt'],
  ['rPlayerItemParam', '.pitm'],
  ['rPlayerConditionParam', '.plcd'],
  ['rPlayerCrystalParam', '.plcr'],
  ['rPlayerModelDefine', '.plmd'],
  ['rPipeMelodyParam', '.pmp'],
  ['rPartnerActionParam', '.pnap'],
  ['rPartnerParam', '.pnp'],
  ['rPartSheet', '.psht'],
  ['rPartnerSkillList', '.psl'],
  ['rProofEffectMotSequenceList', '.pslx'],
  ['rPartnerSkillParam', '.psp'],
  ['rFestaPelTiedSe', '.pts'],
  ['rPlayerParam', '.pwp'],
  ['rQuestSheet', '.qsht'],
  ['rCollision', '.sbc'],
  ['rSoundBank', '.sbkr'],
  ['rServerConstData', '.scd'],
  ['rSoundCurveSet', '.scsr'],
  ['rScheduler', '.sdl'],
  ['rSoundDirectionalSet', '.sdsr'],
  ['rStageData', '.sdtl'],
  ['rShellEffectParam', '.sep'],
  ['rSoundSourceADPCM', '.sew'],
  ['rShell', '.shell'],
  ['rSlotInfo', '.slt'],
  ['rStrengthenNeedMaterialTable', '.snmt'],
  ['rSoundRequest', '.srqr'],
  ['rStoryInfo', '.sti'],
  ['rItemStamp', '.stmp'],
  ['rSoundStreamRequest', '.stqr'],
  ['rSubTargetList', '.sts'],
  ['rSubTargetSet', '.sts'],
  ['rTexture', '.tex'],
  ['rTitleInfo', '.tlif'],
  ['rTechnicalQuestInfo', '.tqi'],
  ['rTechnicalQuestSet', '.tqs'],
  ['rTutorialRouteData', '.trd'],
  ['rVibrationParam', '.vib'],
  ['rWeaponSeries', '.wps'],
  ['rItemZeny', '.zei'],
  ['rZone', '.zon'],
];

/** hash → extension (for extraction) */
export const EXT_BY_HASH = new Map<number, string>();

/** extension → hash (for repacking). Only stores first hash for each extension. */
export const HASH_BY_EXT = new Map<string, number>();

for (const [typeName, ext] of TYPE_EXT_PAIRS) {
  const hash = jamcrc(typeName);
  EXT_BY_HASH.set(hash, ext);
  if (!HASH_BY_EXT.has(ext)) {
    HASH_BY_EXT.set(ext, hash);
  }
}

/** Get file extension for a hash, or fall back to `.{hex}` */
export function getExtension(hash: number): string {
  return EXT_BY_HASH.get(hash) ?? `.${hash.toString(16)}`;
}

/** Get hash for a file extension */
export function getHash(ext: string): number | undefined {
  return HASH_BY_EXT.get(ext);
}
