import mongoose from "mongoose";

const { Schema, model } = mongoose;

const QuestSchema = new Schema({
  clear_time: { type: Number, default: 0 },
  limited_amount: { type: Number, default: 0 }, //amount needed
  mst_limited_id: { type: Number, required: true }, //limited points
  mst_quest_id: { type: Number, required: true },
  quest_subtargets: { type: [Object], default: [] },
  state: { type: Number, required: true }, // Bool for new = 1
});





const NodeInfoSchema = new Schema({
  beginner_node_id: { type: Number, default: 0 },
  hard_polar_node_id: { type: Number, default: 0 },
  kari_polar_node_id: { type: Number, default: 0 },
  new_multi_node_id: { type: Number, default: 0 },
  normal_polar_node_id: { type: Number, default: 0 },
});

const eventSchema = new Schema({
  big_node_order_array: {
    type: [
      {
        big_node_id: { type: Number, required: true },
      },
    ],
    default: [],
  },
  // event_list: {
  //   type: EventListSchema,
  //   default: {
  //     assault: [
  //     ],
  //     m16: [
  //     ],
  //     score: [
  //     ],
  //     standing: [
  //     ],
  //     ticket: [
  //     ],
  //     tour: [
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4230540038,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2374006206,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 344531972,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1670255762,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4260004145,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2330833319,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2353143689,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 357256755,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1649180325,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 443774594,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1836336660,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4257962885,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2328652563,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 3926647542,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 406178011,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1865611341,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4287489500,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2290799946,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 3897384111,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 435659500,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1861259898,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4266627051,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2303246205,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 3918476952,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 481866857,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1807713535,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4211120494,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2349312504,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 3972014109,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 494591582,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1786638024,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4207080281,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2378548175,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 3976350250,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 524050439,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1748717713,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4169420032,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2407759254,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4014273651,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 519965232,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 1777941158,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4182124343,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 2386630561,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //       {
  //         big_node_banner_id: 90005,
  //         middle_node_banner_id: 90035,
  //         mst_event_node_id: 4001799748,
  //         schedule_category: "test",
  //         state: 1,
  //         end_remain: Date.now() + 30 * 24 * 60 * 60 * 1000,
  //         start_remain: Date.now(),
  //       },
  //     ],
  //   },
  // },
  next_day_start: { type: Date },
  next_latest_node_infos: {
    type: NodeInfoSchema,
    default: {
      beginner_node_id: 0,
      hard_polar_node_id: 0,
      kari_polar_node_id: 0,
      new_multi_node_id: 0,
      normal_polar_node_id: 0,
    },
  },
  now_latest_node_info_remain: { type: Date },
  now_latest_node_infos: {
    type: NodeInfoSchema,
    default: {
      beginner_node_id: 0,
      hard_polar_node_id: 0,
      kari_polar_node_id: 0,
      new_multi_node_id: 0,
      normal_polar_node_id: 0,
    },
  },
});

const Event = model("Event", eventSchema);
export default Event;
